apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-ip-demo
  labels:
    app: pop-ip-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pop-ip-demo
  template:
    metadata:
      labels:
        app: pop-ip-demo
    spec:
      containers:
        - name: web
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
          env:
            # 내려보기(Downward API): Pod 이름/IP를 컨테이너에 환경변수로 주입
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  # fieldPath: metadata.name
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: pop-ip-demo
spec:
  selector:
    app: pop-ip-demo
  type: NodePort
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
